name = "XRFast2"
uuid = "ed8862f3-f7e4-4929-aa90-288c2e257ea5"
authors = ["Marc Walton", "Center for Scientific Studies in the Arts"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
